#############################################################################
# Makefile for building: 65088_corriga_andrea
# Generated by qmake (3.0) (Qt 5.7.1)
# Project:  65088_corriga_andrea.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile 65088_corriga_andrea.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DCOMMON_DEFINED -DCOMMON_WITH_EIGEN -DVIEWER_DEFINED -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -std=c++11 -fopenmp -std=c++11 -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I-I -isystem /usr/include/eigen3 -Icommon -Iviewer -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtOpenGL -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = 65088_corriga_andrea1.0.0
DISTDIR = /home/aso/as2-project-AsoStrife/.tmp/65088_corriga_andrea1.0.0
LINK          = g++
LFLAGS        = -m64 -fopenmp -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 /usr/lib/x86_64-linux-gnu/libGLU.so -lQGLViewer-qt5 -lQt5OpenGL -lQt5Widgets -lQt5Gui -lQt5Xml -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = common/common/geometry/line.cpp \
		common/common/geometry/plane.cpp \
		viewer/viewer/glcanvas.cpp \
		viewer/viewer/mainwindow.cpp \
		viewer/viewer/objects/drawabledebugobjects.cpp \
		viewer/viewer/managers/windowmanager.cpp \
		viewer/viewer/interfaces/drawable_mesh.cpp \
		viewer/viewer/drawable_objects/drawableboundingbox2d.cpp \
		main.cpp \
		gui/delaunaymanager.cpp \
		utils/fileutils.cpp \
		utils/delaunay_checker.cpp \
		Andrea/Classes/Drawable/drawabledelaunaytriangulation.cpp \
		Andrea/Classes/Drawable/drawablevoronoidiagram.cpp \
		Andrea/Classes/Static/dag.cpp \
		Andrea/Classes/Static/adjacencies.cpp \
		Andrea/Classes/DataStructures/triangle.cpp \
		Andrea/Classes/DataStructures/dagnode.cpp \
		Andrea/Classes/delaunaytriangulationcore.cpp moc_glcanvas.cpp \
		moc_mainwindow.cpp \
		moc_windowmanager.cpp \
		moc_delaunaymanager.cpp
OBJECTS       = line.o \
		plane.o \
		glcanvas.o \
		mainwindow.o \
		drawabledebugobjects.o \
		windowmanager.o \
		drawable_mesh.o \
		drawableboundingbox2d.o \
		main.o \
		delaunaymanager.o \
		fileutils.o \
		delaunay_checker.o \
		drawabledelaunaytriangulation.o \
		drawablevoronoidiagram.o \
		dag.o \
		adjacencies.o \
		triangle.o \
		dagnode.o \
		delaunaytriangulationcore.o \
		moc_glcanvas.o \
		moc_mainwindow.o \
		moc_windowmanager.o \
		moc_delaunaymanager.o
DIST          = common/common/bounding_box.cpp \
		common/common/timer.cpp \
		common/common/utils.cpp \
		common/common/serialize.cpp \
		common/common/bounding_box2d.cpp \
		viewer/viewer/objects/objects.cpp \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		common/common.pri \
		viewer/viewer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		65088_corriga_andrea.pro common/common/bounding_box.h \
		common/common/comparators.h \
		common/common/point.h \
		common/common/point2d.h \
		common/common/serialize.h \
		common/common/arrays.h \
		common/common/timer.h \
		common/common/utils.h \
		common/common/hashlib.h \
		common/common/file_conversions.h \
		common/common/serializable_object.h \
		common/common/load_save_file.h \
		common/common/color.h \
		common/common/geometry/line.h \
		common/common/geometry/plane.h \
		common/common/bounding_box2d.h \
		viewer/viewer/glcanvas.h \
		viewer/viewer/mainwindow.h \
		viewer/viewer/objects/drawabledebugobjects.h \
		viewer/viewer/managers/windowmanager.h \
		viewer/viewer/objects/objects.h \
		viewer/viewer/interfaces/drawable_object.h \
		viewer/viewer/interfaces/pickable_object.h \
		viewer/viewer/interfaces/drawable_mesh.h \
		viewer/viewer/drawable_objects/drawableboundingbox2d.h \
		gui/delaunaymanager.h \
		utils/fileutils.h \
		utils/delaunay_checker.h \
		Andrea/Headers/Drawable/drawabledelaunaytriangulation.h \
		Andrea/Headers/Drawable/drawablevoronoidiagram.h \
		Andrea/Headers/Static/dag.h \
		Andrea/Headers/Static/adjacencies.h \
		Andrea/Headers/DataStructures/triangle.h \
		Andrea/Headers/DataStructures/dagnode.h \
		Andrea/Headers/delaunaytriangulationcore.h common/common/geometry/line.cpp \
		common/common/geometry/plane.cpp \
		viewer/viewer/glcanvas.cpp \
		viewer/viewer/mainwindow.cpp \
		viewer/viewer/objects/drawabledebugobjects.cpp \
		viewer/viewer/managers/windowmanager.cpp \
		viewer/viewer/interfaces/drawable_mesh.cpp \
		viewer/viewer/drawable_objects/drawableboundingbox2d.cpp \
		main.cpp \
		gui/delaunaymanager.cpp \
		utils/fileutils.cpp \
		utils/delaunay_checker.cpp \
		Andrea/Classes/Drawable/drawabledelaunaytriangulation.cpp \
		Andrea/Classes/Drawable/drawablevoronoidiagram.cpp \
		Andrea/Classes/Static/dag.cpp \
		Andrea/Classes/Static/adjacencies.cpp \
		Andrea/Classes/DataStructures/triangle.cpp \
		Andrea/Classes/DataStructures/dagnode.cpp \
		Andrea/Classes/delaunaytriangulationcore.cpp
QMAKE_TARGET  = 65088_corriga_andrea
DESTDIR       = 
TARGET        = 65088_corriga_andrea


first: all
####### Build rules

$(TARGET): ui_mainwindow.h ui_windowmanager.h ui_delaunaymanager.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: 65088_corriga_andrea.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		common/common.pri \
		viewer/viewer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		65088_corriga_andrea.pro \
		/usr/lib/x86_64-linux-gnu/libQGLViewer-qt5.prl \
		/usr/lib/x86_64-linux-gnu/libQt5OpenGL.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Xml.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile 65088_corriga_andrea.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
common/common.pri:
viewer/viewer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
65088_corriga_andrea.pro:
/usr/lib/x86_64-linux-gnu/libQGLViewer-qt5.prl:
/usr/lib/x86_64-linux-gnu/libQt5OpenGL.prl:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Xml.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile 65088_corriga_andrea.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents common/common/bounding_box.h common/common/comparators.h common/common/point.h common/common/point2d.h common/common/serialize.h common/common/arrays.h common/common/timer.h common/common/utils.h common/common/hashlib.h common/common/file_conversions.h common/common/serializable_object.h common/common/load_save_file.h common/common/color.h common/common/geometry/line.h common/common/geometry/plane.h common/common/bounding_box2d.h viewer/viewer/glcanvas.h viewer/viewer/mainwindow.h viewer/viewer/objects/drawabledebugobjects.h viewer/viewer/managers/windowmanager.h viewer/viewer/objects/objects.h viewer/viewer/interfaces/drawable_object.h viewer/viewer/interfaces/pickable_object.h viewer/viewer/interfaces/drawable_mesh.h viewer/viewer/drawable_objects/drawableboundingbox2d.h gui/delaunaymanager.h utils/fileutils.h utils/delaunay_checker.h Andrea/Headers/Drawable/drawabledelaunaytriangulation.h Andrea/Headers/Drawable/drawablevoronoidiagram.h Andrea/Headers/Static/dag.h Andrea/Headers/Static/adjacencies.h Andrea/Headers/DataStructures/triangle.h Andrea/Headers/DataStructures/dagnode.h Andrea/Headers/delaunaytriangulationcore.h $(DISTDIR)/
	$(COPY_FILE) --parents common/common/geometry/line.cpp common/common/geometry/plane.cpp viewer/viewer/glcanvas.cpp viewer/viewer/mainwindow.cpp viewer/viewer/objects/drawabledebugobjects.cpp viewer/viewer/managers/windowmanager.cpp viewer/viewer/interfaces/drawable_mesh.cpp viewer/viewer/drawable_objects/drawableboundingbox2d.cpp main.cpp gui/delaunaymanager.cpp utils/fileutils.cpp utils/delaunay_checker.cpp Andrea/Classes/Drawable/drawabledelaunaytriangulation.cpp Andrea/Classes/Drawable/drawablevoronoidiagram.cpp Andrea/Classes/Static/dag.cpp Andrea/Classes/Static/adjacencies.cpp Andrea/Classes/DataStructures/triangle.cpp Andrea/Classes/DataStructures/dagnode.cpp Andrea/Classes/delaunaytriangulationcore.cpp $(DISTDIR)/
	$(COPY_FILE) --parents viewer/viewer/mainwindow.ui viewer/viewer/managers/windowmanager.ui gui/delaunaymanager.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_glcanvas.cpp moc_mainwindow.cpp moc_windowmanager.cpp moc_delaunaymanager.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_glcanvas.cpp moc_mainwindow.cpp moc_windowmanager.cpp moc_delaunaymanager.cpp
moc_glcanvas.cpp: common/common/bounding_box.h \
		common/common/point.h \
		common/common/serialize.h \
		common/common/serializable_object.h \
		common/common/serialize.cpp \
		common/common/point.cpp \
		common/common/color.h \
		common/common/color.cpp \
		common/common/bounding_box.cpp \
		common/common/load_save_file.h \
		common/common/load_save_file.cpp \
		viewer/viewer/interfaces/drawable_object.h \
		viewer/viewer/interfaces/pickable_object.h \
		common/common/point2d.h \
		common/common/point2d.cpp \
		viewer/viewer/glcanvas.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/aso/as2-project-AsoStrife -I/home/aso/as2-project-AsoStrife/-I -I/usr/include/eigen3 -I/home/aso/as2-project-AsoStrife/common -I/home/aso/as2-project-AsoStrife/viewer -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include viewer/viewer/glcanvas.h -o moc_glcanvas.cpp

moc_mainwindow.cpp: viewer/viewer/interfaces/drawable_object.h \
		common/common/point.h \
		common/common/serialize.h \
		common/common/serializable_object.h \
		common/common/serialize.cpp \
		common/common/point.cpp \
		viewer/viewer/interfaces/pickable_object.h \
		common/common/bounding_box.h \
		common/common/color.h \
		common/common/color.cpp \
		common/common/bounding_box.cpp \
		common/common/load_save_file.h \
		common/common/load_save_file.cpp \
		viewer/viewer/objects/drawabledebugobjects.h \
		common/common/point2d.h \
		common/common/point2d.cpp \
		viewer/viewer/mainwindow.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/aso/as2-project-AsoStrife -I/home/aso/as2-project-AsoStrife/-I -I/usr/include/eigen3 -I/home/aso/as2-project-AsoStrife/common -I/home/aso/as2-project-AsoStrife/viewer -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include viewer/viewer/mainwindow.h -o moc_mainwindow.cpp

moc_windowmanager.cpp: viewer/viewer/mainwindow.h \
		viewer/viewer/interfaces/drawable_object.h \
		common/common/point.h \
		common/common/serialize.h \
		common/common/serializable_object.h \
		common/common/serialize.cpp \
		common/common/point.cpp \
		viewer/viewer/interfaces/pickable_object.h \
		common/common/bounding_box.h \
		common/common/color.h \
		common/common/color.cpp \
		common/common/bounding_box.cpp \
		common/common/load_save_file.h \
		common/common/load_save_file.cpp \
		viewer/viewer/objects/drawabledebugobjects.h \
		common/common/point2d.h \
		common/common/point2d.cpp \
		viewer/viewer/managers/windowmanager.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/aso/as2-project-AsoStrife -I/home/aso/as2-project-AsoStrife/-I -I/usr/include/eigen3 -I/home/aso/as2-project-AsoStrife/common -I/home/aso/as2-project-AsoStrife/viewer -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include viewer/viewer/managers/windowmanager.h -o moc_windowmanager.cpp

moc_delaunaymanager.cpp: viewer/viewer/mainwindow.h \
		viewer/viewer/interfaces/drawable_object.h \
		common/common/point.h \
		common/common/serialize.h \
		common/common/serializable_object.h \
		common/common/serialize.cpp \
		common/common/point.cpp \
		viewer/viewer/interfaces/pickable_object.h \
		common/common/bounding_box.h \
		common/common/color.h \
		common/common/color.cpp \
		common/common/bounding_box.cpp \
		common/common/load_save_file.h \
		common/common/load_save_file.cpp \
		viewer/viewer/objects/drawabledebugobjects.h \
		common/common/point2d.h \
		common/common/point2d.cpp \
		viewer/viewer/drawable_objects/drawableboundingbox2d.h \
		common/common/bounding_box2d.h \
		common/common/bounding_box2d.cpp \
		Andrea/Headers/delaunaytriangulationcore.h \
		Andrea/Headers/DataStructures/dagnode.h \
		viewer/viewer/objects/objects.h \
		viewer/viewer/objects/objects.cpp \
		Andrea/Headers/DataStructures/triangle.h \
		Andrea/Headers/Static/adjacencies.h \
		Andrea/Headers/Static/dag.h \
		utils/delaunay_checker.h \
		common/common/utils.h \
		common/common/utils.cpp \
		common/common/arrays.h \
		common/common/arrays.cpp \
		Andrea/Headers/Drawable/drawabledelaunaytriangulation.h \
		Andrea/Headers/Drawable/drawablevoronoidiagram.h \
		gui/delaunaymanager.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/aso/as2-project-AsoStrife -I/home/aso/as2-project-AsoStrife/-I -I/usr/include/eigen3 -I/home/aso/as2-project-AsoStrife/common -I/home/aso/as2-project-AsoStrife/viewer -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include gui/delaunaymanager.h -o moc_delaunaymanager.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_windowmanager.h ui_delaunaymanager.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_windowmanager.h ui_delaunaymanager.h
ui_mainwindow.h: viewer/viewer/mainwindow.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic \
		viewer/viewer/glcanvas.h \
		common/common/bounding_box.h \
		common/common/point.h \
		common/common/serialize.h \
		common/common/serializable_object.h \
		common/common/serialize.cpp \
		common/common/point.cpp \
		common/common/color.h \
		common/common/color.cpp \
		common/common/bounding_box.cpp \
		common/common/load_save_file.h \
		common/common/load_save_file.cpp \
		viewer/viewer/interfaces/drawable_object.h \
		viewer/viewer/interfaces/pickable_object.h \
		common/common/point2d.h \
		common/common/point2d.cpp
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic viewer/viewer/mainwindow.ui -o ui_mainwindow.h

ui_windowmanager.h: viewer/viewer/managers/windowmanager.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic viewer/viewer/managers/windowmanager.ui -o ui_windowmanager.h

ui_delaunaymanager.h: gui/delaunaymanager.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic gui/delaunaymanager.ui -o ui_delaunaymanager.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

line.o: common/common/geometry/line.cpp common/common/geometry/line.h \
		common/common/point.h \
		common/common/serialize.h \
		common/common/serializable_object.h \
		common/common/serialize.cpp \
		common/common/point.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o line.o common/common/geometry/line.cpp

plane.o: common/common/geometry/plane.cpp common/common/geometry/plane.h \
		common/common/point.h \
		common/common/serialize.h \
		common/common/serializable_object.h \
		common/common/serialize.cpp \
		common/common/point.cpp \
		common/common/geometry/line.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o plane.o common/common/geometry/plane.cpp

glcanvas.o: viewer/viewer/glcanvas.cpp viewer/viewer/glcanvas.h \
		common/common/bounding_box.h \
		common/common/point.h \
		common/common/serialize.h \
		common/common/serializable_object.h \
		common/common/serialize.cpp \
		common/common/point.cpp \
		common/common/color.h \
		common/common/color.cpp \
		common/common/bounding_box.cpp \
		common/common/load_save_file.h \
		common/common/load_save_file.cpp \
		viewer/viewer/interfaces/drawable_object.h \
		viewer/viewer/interfaces/pickable_object.h \
		common/common/point2d.h \
		common/common/point2d.cpp \
		common/common/geometry/plane.h \
		common/common/geometry/line.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o glcanvas.o viewer/viewer/glcanvas.cpp

mainwindow.o: viewer/viewer/mainwindow.cpp viewer/viewer/mainwindow.h \
		viewer/viewer/interfaces/drawable_object.h \
		common/common/point.h \
		common/common/serialize.h \
		common/common/serializable_object.h \
		common/common/serialize.cpp \
		common/common/point.cpp \
		viewer/viewer/interfaces/pickable_object.h \
		common/common/bounding_box.h \
		common/common/color.h \
		common/common/color.cpp \
		common/common/bounding_box.cpp \
		common/common/load_save_file.h \
		common/common/load_save_file.cpp \
		viewer/viewer/objects/drawabledebugobjects.h \
		common/common/point2d.h \
		common/common/point2d.cpp \
		ui_mainwindow.h \
		common/common/geometry/plane.h \
		common/common/geometry/line.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o viewer/viewer/mainwindow.cpp

drawabledebugobjects.o: viewer/viewer/objects/drawabledebugobjects.cpp viewer/viewer/objects/drawabledebugobjects.h \
		viewer/viewer/interfaces/drawable_object.h \
		common/common/point.h \
		common/common/serialize.h \
		common/common/serializable_object.h \
		common/common/serialize.cpp \
		common/common/point.cpp \
		common/common/bounding_box.h \
		common/common/color.h \
		common/common/color.cpp \
		common/common/bounding_box.cpp \
		common/common/load_save_file.h \
		common/common/load_save_file.cpp \
		viewer/viewer/objects/objects.h \
		common/common/point2d.h \
		common/common/point2d.cpp \
		viewer/viewer/objects/objects.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o drawabledebugobjects.o viewer/viewer/objects/drawabledebugobjects.cpp

windowmanager.o: viewer/viewer/managers/windowmanager.cpp viewer/viewer/managers/windowmanager.h \
		viewer/viewer/mainwindow.h \
		viewer/viewer/interfaces/drawable_object.h \
		common/common/point.h \
		common/common/serialize.h \
		common/common/serializable_object.h \
		common/common/serialize.cpp \
		common/common/point.cpp \
		viewer/viewer/interfaces/pickable_object.h \
		common/common/bounding_box.h \
		common/common/color.h \
		common/common/color.cpp \
		common/common/bounding_box.cpp \
		common/common/load_save_file.h \
		common/common/load_save_file.cpp \
		viewer/viewer/objects/drawabledebugobjects.h \
		common/common/point2d.h \
		common/common/point2d.cpp \
		ui_windowmanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o windowmanager.o viewer/viewer/managers/windowmanager.cpp

drawable_mesh.o: viewer/viewer/interfaces/drawable_mesh.cpp viewer/viewer/interfaces/drawable_mesh.h \
		viewer/viewer/objects/objects.h \
		common/common/point.h \
		common/common/serialize.h \
		common/common/serializable_object.h \
		common/common/serialize.cpp \
		common/common/point.cpp \
		common/common/point2d.h \
		common/common/point2d.cpp \
		viewer/viewer/objects/objects.cpp \
		viewer/viewer/interfaces/drawable_object.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o drawable_mesh.o viewer/viewer/interfaces/drawable_mesh.cpp

drawableboundingbox2d.o: viewer/viewer/drawable_objects/drawableboundingbox2d.cpp viewer/viewer/drawable_objects/drawableboundingbox2d.h \
		common/common/bounding_box2d.h \
		common/common/point2d.h \
		common/common/serialize.h \
		common/common/serializable_object.h \
		common/common/serialize.cpp \
		common/common/point2d.cpp \
		common/common/bounding_box2d.cpp \
		common/common/color.h \
		common/common/color.cpp \
		viewer/viewer/interfaces/drawable_object.h \
		common/common/point.h \
		common/common/point.cpp \
		viewer/viewer/objects/objects.h \
		viewer/viewer/objects/objects.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o drawableboundingbox2d.o viewer/viewer/drawable_objects/drawableboundingbox2d.cpp

main.o: main.cpp common/common/arrays.h \
		common/common/serialize.h \
		common/common/serializable_object.h \
		common/common/serialize.cpp \
		common/common/arrays.cpp \
		common/common/bounding_box.h \
		common/common/point.h \
		common/common/point.cpp \
		common/common/color.h \
		common/common/color.cpp \
		common/common/bounding_box.cpp \
		common/common/load_save_file.h \
		common/common/load_save_file.cpp \
		common/common/comparators.h \
		common/common/timer.h \
		common/common/timer.cpp \
		viewer/viewer/interfaces/drawable_object.h \
		viewer/viewer/interfaces/pickable_object.h \
		viewer/viewer/mainwindow.h \
		viewer/viewer/objects/drawabledebugobjects.h \
		common/common/point2d.h \
		common/common/point2d.cpp \
		viewer/viewer/managers/windowmanager.h \
		gui/delaunaymanager.h \
		viewer/viewer/drawable_objects/drawableboundingbox2d.h \
		common/common/bounding_box2d.h \
		common/common/bounding_box2d.cpp \
		Andrea/Headers/delaunaytriangulationcore.h \
		Andrea/Headers/DataStructures/dagnode.h \
		viewer/viewer/objects/objects.h \
		viewer/viewer/objects/objects.cpp \
		Andrea/Headers/DataStructures/triangle.h \
		Andrea/Headers/Static/adjacencies.h \
		Andrea/Headers/Static/dag.h \
		utils/delaunay_checker.h \
		common/common/utils.h \
		common/common/utils.cpp \
		Andrea/Headers/Drawable/drawabledelaunaytriangulation.h \
		Andrea/Headers/Drawable/drawablevoronoidiagram.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

delaunaymanager.o: gui/delaunaymanager.cpp gui/delaunaymanager.h \
		viewer/viewer/mainwindow.h \
		viewer/viewer/interfaces/drawable_object.h \
		common/common/point.h \
		common/common/serialize.h \
		common/common/serializable_object.h \
		common/common/serialize.cpp \
		common/common/point.cpp \
		viewer/viewer/interfaces/pickable_object.h \
		common/common/bounding_box.h \
		common/common/color.h \
		common/common/color.cpp \
		common/common/bounding_box.cpp \
		common/common/load_save_file.h \
		common/common/load_save_file.cpp \
		viewer/viewer/objects/drawabledebugobjects.h \
		common/common/point2d.h \
		common/common/point2d.cpp \
		viewer/viewer/drawable_objects/drawableboundingbox2d.h \
		common/common/bounding_box2d.h \
		common/common/bounding_box2d.cpp \
		Andrea/Headers/delaunaytriangulationcore.h \
		Andrea/Headers/DataStructures/dagnode.h \
		viewer/viewer/objects/objects.h \
		viewer/viewer/objects/objects.cpp \
		Andrea/Headers/DataStructures/triangle.h \
		Andrea/Headers/Static/adjacencies.h \
		Andrea/Headers/Static/dag.h \
		utils/delaunay_checker.h \
		common/common/utils.h \
		common/common/utils.cpp \
		common/common/arrays.h \
		common/common/arrays.cpp \
		Andrea/Headers/Drawable/drawabledelaunaytriangulation.h \
		Andrea/Headers/Drawable/drawablevoronoidiagram.h \
		ui_delaunaymanager.h \
		utils/fileutils.h \
		common/common/timer.h \
		common/common/timer.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o delaunaymanager.o gui/delaunaymanager.cpp

fileutils.o: utils/fileutils.cpp utils/fileutils.h \
		common/common/point2d.h \
		common/common/serialize.h \
		common/common/serializable_object.h \
		common/common/serialize.cpp \
		common/common/point2d.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fileutils.o utils/fileutils.cpp

delaunay_checker.o: utils/delaunay_checker.cpp utils/delaunay_checker.h \
		common/common/point2d.h \
		common/common/serialize.h \
		common/common/serializable_object.h \
		common/common/serialize.cpp \
		common/common/point2d.cpp \
		common/common/utils.h \
		common/common/point.h \
		common/common/point.cpp \
		common/common/color.h \
		common/common/color.cpp \
		common/common/utils.cpp \
		common/common/arrays.h \
		common/common/arrays.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o delaunay_checker.o utils/delaunay_checker.cpp

drawabledelaunaytriangulation.o: Andrea/Classes/Drawable/drawabledelaunaytriangulation.cpp Andrea/Headers/Drawable/drawabledelaunaytriangulation.h \
		viewer/viewer/objects/objects.h \
		common/common/point.h \
		common/common/serialize.h \
		common/common/serializable_object.h \
		common/common/serialize.cpp \
		common/common/point.cpp \
		common/common/point2d.h \
		common/common/point2d.cpp \
		viewer/viewer/objects/objects.cpp \
		Andrea/Headers/DataStructures/triangle.h \
		Andrea/Headers/Static/adjacencies.h \
		Andrea/Headers/Static/dag.h \
		Andrea/Headers/DataStructures/dagnode.h \
		viewer/viewer/interfaces/drawable_object.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o drawabledelaunaytriangulation.o Andrea/Classes/Drawable/drawabledelaunaytriangulation.cpp

drawablevoronoidiagram.o: Andrea/Classes/Drawable/drawablevoronoidiagram.cpp Andrea/Headers/Drawable/drawablevoronoidiagram.h \
		viewer/viewer/objects/objects.h \
		common/common/point.h \
		common/common/serialize.h \
		common/common/serializable_object.h \
		common/common/serialize.cpp \
		common/common/point.cpp \
		common/common/point2d.h \
		common/common/point2d.cpp \
		viewer/viewer/objects/objects.cpp \
		viewer/viewer/interfaces/drawable_object.h \
		Andrea/Headers/DataStructures/triangle.h \
		Andrea/Headers/Static/adjacencies.h \
		Andrea/Headers/Static/dag.h \
		Andrea/Headers/DataStructures/dagnode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o drawablevoronoidiagram.o Andrea/Classes/Drawable/drawablevoronoidiagram.cpp

dag.o: Andrea/Classes/Static/dag.cpp Andrea/Headers/Static/dag.h \
		viewer/viewer/objects/objects.h \
		common/common/point.h \
		common/common/serialize.h \
		common/common/serializable_object.h \
		common/common/serialize.cpp \
		common/common/point.cpp \
		common/common/point2d.h \
		common/common/point2d.cpp \
		viewer/viewer/objects/objects.cpp \
		Andrea/Headers/Static/adjacencies.h \
		Andrea/Headers/DataStructures/triangle.h \
		Andrea/Headers/DataStructures/dagnode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dag.o Andrea/Classes/Static/dag.cpp

adjacencies.o: Andrea/Classes/Static/adjacencies.cpp Andrea/Headers/Static/adjacencies.h \
		Andrea/Headers/DataStructures/triangle.h \
		viewer/viewer/objects/objects.h \
		common/common/point.h \
		common/common/serialize.h \
		common/common/serializable_object.h \
		common/common/serialize.cpp \
		common/common/point.cpp \
		common/common/point2d.h \
		common/common/point2d.cpp \
		viewer/viewer/objects/objects.cpp \
		Andrea/Headers/Static/dag.h \
		Andrea/Headers/DataStructures/dagnode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o adjacencies.o Andrea/Classes/Static/adjacencies.cpp

triangle.o: Andrea/Classes/DataStructures/triangle.cpp Andrea/Headers/DataStructures/triangle.h \
		viewer/viewer/objects/objects.h \
		common/common/point.h \
		common/common/serialize.h \
		common/common/serializable_object.h \
		common/common/serialize.cpp \
		common/common/point.cpp \
		common/common/point2d.h \
		common/common/point2d.cpp \
		viewer/viewer/objects/objects.cpp \
		Andrea/Headers/Static/adjacencies.h \
		Andrea/Headers/Static/dag.h \
		Andrea/Headers/DataStructures/dagnode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o triangle.o Andrea/Classes/DataStructures/triangle.cpp

dagnode.o: Andrea/Classes/DataStructures/dagnode.cpp Andrea/Headers/DataStructures/dagnode.h \
		viewer/viewer/objects/objects.h \
		common/common/point.h \
		common/common/serialize.h \
		common/common/serializable_object.h \
		common/common/serialize.cpp \
		common/common/point.cpp \
		common/common/point2d.h \
		common/common/point2d.cpp \
		viewer/viewer/objects/objects.cpp \
		Andrea/Headers/DataStructures/triangle.h \
		Andrea/Headers/Static/adjacencies.h \
		Andrea/Headers/Static/dag.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dagnode.o Andrea/Classes/DataStructures/dagnode.cpp

delaunaytriangulationcore.o: Andrea/Classes/delaunaytriangulationcore.cpp Andrea/Headers/delaunaytriangulationcore.h \
		Andrea/Headers/DataStructures/dagnode.h \
		viewer/viewer/objects/objects.h \
		common/common/point.h \
		common/common/serialize.h \
		common/common/serializable_object.h \
		common/common/serialize.cpp \
		common/common/point.cpp \
		common/common/point2d.h \
		common/common/point2d.cpp \
		viewer/viewer/objects/objects.cpp \
		Andrea/Headers/DataStructures/triangle.h \
		Andrea/Headers/Static/adjacencies.h \
		Andrea/Headers/Static/dag.h \
		utils/delaunay_checker.h \
		common/common/utils.h \
		common/common/color.h \
		common/common/color.cpp \
		common/common/utils.cpp \
		common/common/arrays.h \
		common/common/arrays.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o delaunaytriangulationcore.o Andrea/Classes/delaunaytriangulationcore.cpp

moc_glcanvas.o: moc_glcanvas.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_glcanvas.o moc_glcanvas.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_windowmanager.o: moc_windowmanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_windowmanager.o moc_windowmanager.cpp

moc_delaunaymanager.o: moc_delaunaymanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_delaunaymanager.o moc_delaunaymanager.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

